### ISSUE TITLE
magithub doesn't detect Github remotes using insteadOf shortcuts

### ISSUE THREAD

**Issue by hyperair** [vermiculus/magithub#365] opened 2018-08-27 04:43 UTC
In my `.gitconfig`, I have a snippet that looks like this:

```
[url "git@github.com:"]
    insteadOf = gh:
```

This allows me to clone github repos using `gh:user/repo` as the clone URL. `magithub` doesn't detect these as Github repositories by default although `git remote get-url origin` shows the full `git@github.com:user/repo` URL.

**Comment by vermiculus** [comment] 2018-08-27 20:33
Duplicate of #324

**Closed by vermiculus** 2018-08-27 20:33 UTC
