### ISSUE TITLE
Invalid-function magithub-with-proxy

### ISSUE THREAD

**Issue by aaronjensen** [vermiculus/magithub#69] opened 2017-02-13 18:57 UTC
This is with latest melpa magit and magithub via spacemacs as of this morning when I open magit status:

```
Debugger entered--Lisp error: (invalid-function magithub-with-proxy)
  magithub-with-proxy(nil nil)
  magithub-issue--insert-pr-section()
  run-hooks(magit-status-sections-hook)
  magit-status-refresh-buffer()
  apply(magit-status-refresh-buffer nil)
  magit-refresh-buffer()
  magit-mode-setup-internal(magit-status-mode nil)
  magit-mode-setup(magit-status-mode)
  magit-status-internal("/Users/aaronjensen/.subscript/")
  magit-status(nil)
  funcall-interactively(magit-status nil)
  call-interactively(magit-status nil nil)
  command-execute(magit-status)
```

Thanks!

**Comment by vermiculus** [comment] 2017-02-13 19:18
Duplicate of #68

**Closed by vermiculus** 2017-02-13 19:18 UTC
