### ISSUE TITLE
:condition-case must be a list of error handlers; see the documentation: ((ghub-422

### ISSUE THREAD

**Issue by simendsjo** [vermiculus/magithub#382] opened 2018-10-23 18:44 UTC
Ref https://github.com/vermiculus/magithub/issues/301#issuecomment-432140677

```
Eager macro-expansion failure: (error ":condition-case must be a list of error handlers; see the documentation: ((ghub-422 (signal (quote ghubp-error-review-is-active) nil)) (ghub-http-error (let* ((val (car (cdr it)))) (if (eq val 422) (progn (signal (quote ghubp-error-review-is-active) nil)) (signal (car it) (cdr it))))))") [2 times]
```

```
apiwrap-gendefun: :condition-case must be a list of error handlers; see the documentation: ((ghub-422 (signal (quote ghubp-error-review-is-active) nil)) (ghub-http-error (let* ((val (car (cdr it)))) (if (eq val 422) (progn (signal (quote ghubp-error-review-is-active) nil)) (signal (car it) (cdr it))))))
```

**Comment by vermiculus** [comment] 2018-10-23 19:05
Duplicate of vermiculus/ghub-plus#13

**Closed by vermiculus** 2018-10-23 19:05 UTC
