### ISSUE TITLE
How to address "API call resulted in error; go offline? (y or n)"

### ISSUE THREAD

**Issue by jabranham** [vermiculus/magithub#107] opened 2017-06-14 06:14 UTC
I get this message from magithub every now and then. I hit y, then H O and it reconnects without issue.

Sorry for being vague. I'm just not sure what the issue is.

**Comment by vermiculus** [comment] 2017-06-14 13:39
This seems to be a recurring problem with different kinds of networks. I've never personally had this issue, but this seems to be a recurring problem for quite a few people. I'm looking into different ways of testing whether the API is available.

After this is fixed, I'll tag a new version (cf #108).

...You'd think this would be a *simple* problem.

**Comment by zenspider** [comment] 2017-06-19 06:35
@jabranham looking at the source the default timeout is 1 second. You might want to increase that to avoid getting the question as much. I don't get it at home, but get it frequently if on a café network.

I think you can also hit 'n', and it'll trudge through.

**Comment by FrancescElies** [comment] 2017-06-20 13:55
Hi, 

not sure if this is the same issue, but I'm also getting the message
`API call resulted in error` but I get it on all networks for some time now, maybe I broke something in my configuration, not sure though.

I'm pretty sure I did something wrong with it. How could I provide a more details about the issue?
Git and Magit work fine in my environment.
Any ideas what things could I check?

All best & thanks

**Comment by vermiculus** [comment] 2017-06-20 13:57
@FrancescElies Set `magithub-debug` to `t` and reproduce the problem, then check `*Messages*.

**Comment by FrancescElies** [comment] 2017-06-20 15:31
Thanks, so my issue was not related to this one.
Something was going on with my token, inside my authinfo I had `machine github.com login myUser password myPassword` but I should have `machine api.github.com login myUser password myPassword`

All best & thanks for your help

**Comment by jackson15j** [comment] 2017-06-26 15:49
Possibly also a red-herring on my part for trying this exclusively with my works enterprise github instance (and failing), but here is my debug output:

```
[C-t] show common commands, [?] describe events, [C-h i] show manual
magithub: (43:38.936) checking if the API is available
magithub: (43:38.937) retrieving new value for api-available-p
magithub: (43:38.937) ghub--request("GET" "/rate_limit" nil nil nil)
Contacting host: exampleenterpise-github.domain.com:443
magithub: (43:39.793) new value retrieved for api-available-p
magithub: (43:39.794) (ghub-404 "GET" "/rate_limit" nil nil ((message . "Rate limiting is not enabled.") (documentation_url . "https://developer.github.com/enterprise/2.9/v3")))
API call resulted in error; go offline? (y or n) n
```

Can confirm that our work instance has rate limiting disabled, which I guess needs to be explicitly caught by this module or [ghub](https://github.com/tarsius/ghub).

**Comment by daemianmack** [comment] 2017-06-30 14:46
I was seeing this error and resolved it by...

1. Evaluating `(setq magithub-debug-mode t)` in the `*scratch*` buffer and re-executing `magit-status`, which produced the following in the `*Messages*` buffer...

```
[2017-06-30T10:27:20.143742] magithub: (27:20.143) checking if the API is available
[2017-06-30T10:27:20.144056] magithub: (27:20.144) retrieving new value for api-available-p
[2017-06-30T10:27:20.144200] magithub: (27:20.144) ghub--request("GET" "/rate_limit" nil nil nil)
[2017-06-30T10:27:20.148347] magithub: (27:20.148) new value retrieved for api-available-p
[2017-06-30T10:27:20.148573] magithub: (27:20.148) (args-out-of-range "" 0 -1)
[2017-06-30T10:27:21.523142]
[2017-06-30T10:27:21.523474] API call resulted in error; go offline? (y or n) n
```


2. which led me to investigate the callpath from `magithub` through `ghub.el+` and `ghub.el` to the underlying `hub` binary, which eventually uncovered that I needed to follow the instructions at the top of the [ghub README](https://github.com/tarsius/ghub/blob/efdc28e3d27dd0847ceece593ecd1e9ed3287c9f/README.md)...

```
$ git config --global github.user <username>
$ emacs ~/.authinfo.gpg
# -*- epa-file-encrypt-to: ("A.U.Thor@example.com") -*-
machine api.github.com login <login> password <token>
```

Not sure why this wasn't necessary prior to now, but now the call works.

**Comment by jackson15j** [comment] 2017-07-18 16:52
@daemianmack, it looks like I have a different issue to you. Via hub and ghub I can get results back from API calls to my works Github Enterprise server. Instead I'm seeing an issue with Magithub's handling in `magithub--api-available-p` in magithub-core.el when the enterprise server has rate limiting disabled.

Reproduction:

* Company Github Enterprise server has rate limiting disabled.
* Confirm hub (on cli) and ghub can access paths. eg. `(ghub-get "/users/<user>/repos")` returns expected public repos.
* Confirm any restclient or ghub: `(ghub-get "/rate_limit")` returns the elisp equivalent of the following in a 404 response:

```
{
  "message": "Rate limiting is not enabled.",
  "documentation_url": "https://developer.github.com/enterprise/2.9/v3"
}
```

* `magit--api-available-p` in magithub-core.el does a check that the above `ghub-get` returns 200.
* Hack: Commenting out this functions body and reloading the library gets magithub working for me.

In this very specific case I believe there should be a check on the `message` line to handle the situation when rate limiting is disabled. Or use a different path to check for API _aliveness_.

Note: Annoyingly there isn't a mention of what response they return when rate limiting is disabled: https://developer.github.com/v3/rate_limit/. Personally I would've expected a 200 and a `0`/`-1` value when it is disabled.

**Comment by vermiculus** [comment] 2017-07-18 17:09
If anyone is able to provide me with any kind of access to an Enterprise server, that might help me in resolving this issue -- otherwise I can rely on PRs.

I haven't been able to work on this project for some time (sorry!), but I believe I am currently checking a different path for 'aliveness' on my dev box. Ideally, rate-limiting itself will be handled by `ghub` looking at response headers. I *think* right now I'm considering using `/meta`.

**Comment by drielsma** [comment] 2017-07-20 15:09
Those who use `magithub` with GHE may, like me, be running into https://github.com/tarsius/ghub/issues/21

**Comment by cranehuang** [comment] 2017-07-24 03:19
I have the same problem. It is caused by the gpg configuration on my mac. If someone has the same issue, you may read this [tutorial](https://gist.github.com/bcomnes/647477a3a143774069755d672cb395ca), it helps me a lot.

**Comment by vermiculus** [comment] 2017-08-05 11:01
Since this is a bunch of issues rolled into one, here's a summary list of comments on this thread.

- [] API availability check gives false positives @jabranham @zenspider 
- [] Unclear message when the error is an authentication issue @FrancescElies 
- [] Support instances where rate-limiting is disabled @jackson15j @daemianmack (which note we don't use the `hub` binary anymore as of #79…) @drielsma  @cranehuang

**Closed** 2017-08-05 11:04 UTC
Labels: bug

**Comment by vermiculus** [comment] 2017-08-05 11:06
As promised, I'll tag a new version (to close #108) if I see that these recent changes have resolved the issue 'enough' to do so.

Folks I've mentioned above: is the new behavior *better* than it was before? Is it unchanged? (Perish the thought… but is it *worse*?) Please let me know.

**Comment by jabranham** [comment] 2017-08-13 18:57
Thanks for the changes. This seems to work much better, at least for me!
