### ISSUE TITLE
Is it possible to create an issue without label?

### ISSUE THREAD

**Issue by yashi** [vermiculus/magithub#366] opened 2018-08-30 05:06 UTC
When I tried to create a new issue with magithub, it asked me to put a label on it.  Is it possible to submit an issue without any label?

**Comment by vermiculus** [comment] 2018-09-04 15:35
Yes. You will have to refer to the documentation for your completion system to do so. Under Ivy, this idea is called 'accepting the current input', which in your case is null. Under Ivy, this can be done with C-M-j.

**Comment by vermiculus** [comment] 2018-09-08 12:09
Duplicate of #347

**Closed** 2018-09-08 12:10 UTC
Labels: question
