### ISSUE TITLE
Not Found if repository url doesn't end with ".git"

### ISSUE THREAD

**Issue by spebern** [vermiculus/magithub#111] opened 2017-07-12 15:39 UTC
If I execute magit-status in certain repos I get the following error:
```Not Found: "GET", "/repos/////issues", nil, nil, ((message . "Not Found") (documentation_url "https://developer.github.com/v3"))```

The repository url returned by ```(magit-get "remote" (magithub-source--remote) "url")``` is ```git@github.com:spebern/Bailador```

As soon as a repositry url does not end with ".git" it won't match the regex parsing that url, because
".git" is not optional.

**Comment by zakame** [comment] 2017-07-19 11:02
Just ran into this my now, mainly on Go repos fetched via `go get`.

**Comment by vermiculus** [comment] 2017-07-19 12:55
@zakame, do you have steps to reproduce? :-)

**Comment by zakame** [comment] 2017-07-19 13:24
@vermiculus sure, for me it was getting [docker-machine-kvm](https://github.com/dhiltgen/docker-machine-kvm) via `go get`:

```sh
[zakame:~] 2 % GOPATH=~/altgo go get -u -v -x github.com/dhiltgen/docker-machine-kvm 
github.com/dhiltgen/docker-machine-kvm (download)
created GOPATH=/home/zakame/altgo; see 'go help gopath'
cd .
git clone https://github.com/dhiltgen/docker-machine-kvm /home/zakame/altgo/src/github.com/dhiltgen/docker-machine-kvm
cd /home/zakame/altgo/src/github.com/dhiltgen/docker-machine-kvm
git submodule update --init --recursive
cd /home/zakame/altgo/src/github.com/dhiltgen/docker-machine-kvm
git show-ref
cd /home/zakame/altgo/src/github.com/dhiltgen/docker-machine-kvm
git submodule update --init --recursive
github.com/docker/machine (download)
cd .
git clone https://github.com/docker/machine /home/zakame/altgo/src/github.com/docker/machine
cd /home/zakame/altgo/src/github.com/docker/machine
git submodule update --init --recursive
cd /home/zakame/altgo/src/github.com/docker/machine
git show-ref
cd /home/zakame/altgo/src/github.com/docker/machine
git submodule update --init --recursive
cd /home/zakame/altgo/src/github.com/docker/machine
git config remote.origin.url
cd /home/zakame/altgo/src/github.com/docker/machine
git config remote.origin.url
cd /home/zakame/altgo/src/github.com/docker/machine
git config remote.origin.url
cd /home/zakame/altgo/src/github.com/docker/machine
git config remote.origin.url
cd /home/zakame/altgo/src/github.com/docker/machine
git config remote.origin.url
cd /home/zakame/altgo/src/github.com/docker/machine
git config remote.origin.url
cd /home/zakame/altgo/src/github.com/docker/machine
git config remote.origin.url
github.com/libvirt/libvirt-go (download)
cd .
git clone https://github.com/libvirt/libvirt-go /home/zakame/altgo/src/github.com/libvirt/libvirt-go
cd /home/zakame/altgo/src/github.com/libvirt/libvirt-go
git submodule update --init --recursive
cd /home/zakame/altgo/src/github.com/libvirt/libvirt-go
git show-ref
cd /home/zakame/altgo/src/github.com/libvirt/libvirt-go
git submodule update --init --recursive
WORK=/tmp/go-build974707010
...
cp $WORK/github.com/dhiltgen/docker-machine-kvm.a /home/zakame/altgo/pkg/linux_amd64/github.com/dhiltgen/docker-machine-kvm.a
θ71° [zakame:~] 10m12s % 
```

Note that the `git clone`s above does use the GitHub URL of the repo directly, not the proper `.git` URL, so I suppose this might be a Go issue as well.  Visiting any  repos `~/altgo/src/github.com/` with magithub results in 

```
Not Found: "GET", "/repos/////issues", nil, nil, ((message . "Not Found") (documentation_url . "https://developer.github.com/v3"))
```

which I think might be caused by `magithub--url->repo` failing to match what remote it can find in `.git/config`.

**Comment by vermiculus** [comment] 2017-07-30 01:49
Related to #105

**Comment by vermiculus** [comment] 2017-07-30 03:51
Closing as a dupe of #105. Thanks for the information though – it was invaluable!

**Closed by vermiculus** 2017-07-30 03:51 UTC
Labels: bug

**Comment by zakame** [comment] 2017-07-30 03:54
Thanks @vermiculus @spebern !
