### ISSUE TITLE
Toggle to offline fails

### ISSUE THREAD

**Issue by drielsma** [vermiculus/magithub#290] opened 2018-02-23 16:42 UTC
`H O` to toggle to offline fails for me using magithub `20180217.601` installed from melpa

I'm running `HEAD`, `GNU Emacs 27.0.50` installed via brew. That might account for it too. I will try to reproduce on something stable.

```
Debugger entered--Lisp error: (wrong-type-argument commandp magithub-toggle-online)
  call-interactively(magithub-toggle-online)
  magit-invoke-popup-action(79)
  funcall-interactively(magit-invoke-popup-action 79)
  call-interactively(magit-invoke-popup-action nil nil)
  command-execute(magit-invoke-popup-action)
```

**Comment by vermiculus** [comment] 2018-02-23 23:46
`HEAD` is probably more stable than a stable release at this point. See #219.

Closing as a duplicate of #287.

**Closed by vermiculus** 2018-02-23 23:46 UTC

**Comment by drielsma** [comment] 2018-02-24 01:59
Cool, thanks.
