### ISSUE TITLE
symbol's function definition is void 

### ISSUE THREAD

**Issue by anquegi** [vermiculus/magithub#128] opened 2017-08-17 15:21 UTC
Thanks for this great libaryI'm using magithub and magit (I'm using cask), 

```
ls magit*                                                                                                                                                               
magit-20170808.1712:
magit-gerrit-20160226.130:
magit-popup-20170810.917:   
magithub-20170810.1947:
```

separately it works fine:

<img width="1280" alt="captura de pantalla 2017-08-17 a las 16 56 49" src="https://user-images.githubusercontent.com/2518346/29418607-19d8415c-836d-11e7-8f57-316b927b3a6b.png">

then I add this lines, it worked well in the beginnign, but after installing Ztree (I do not thing if this is relevant) it doesn't work:

```
(use-package magithub
  :after magit
  :config (magithub-feature-autoinject t))
```
<img width="1280" alt="captura de pantalla 2017-08-17 a las 17 05 02" src="https://user-images.githubusercontent.com/2518346/29419010-4624bf14-836e-11e7-9728-6b3c46240f5b.png">

with this messages:

```
Contacting host: api.github.com:443
*CLING*CLING*
apply: Symbol’s function definition is void: nil
```

and if I catch the debugger on error  (M-x toggle-debug-on-error) I get this:

*messages* buffer

```
magithub: (10:17.627) checking if the API is available
magithub: (10:17.627) making sure authinfo is unlocked
magithub: (10:17.628) cache expired; retrieving new value for api-last-checked
magithub: (10:17.628) ghub-request("GET" "/rate_limit" nil nil nil)
Contacting host: api.github.com:443
magithub: (10:18.257) new value retrieved for api-last-available: ((resources (core (limit . 5000) (remaining . 5000) (reset . 1502986218)) (search (limit . 30) (remaining . 30) (reset . 1502982678)) (graphql (limit . 5000) (remaining . 5000) (reset . 1502986218))) (rate (limit . 5000) (remaining . 5000) (reset . 1502986218)))
Entering debugger...
```

*Backtrace* buffer

```
Debugger entered--Lisp error: (void-function nil)
  nil("/repos/anquegi/.emacs.public.d" nil nil)
  apply(nil "/repos/anquegi/.emacs.public.d" (nil nil))
  ghubp-get-repos-owner-repo(((owner (login . "anquegi")) (name . ".emacs.public.d")))
  (or (ghubp-get-repos-owner-repo (quote ((owner (login . "anquegi")) (name . ".emacs.public.d")))) (and (not magithub--api-available-p) sparse))
  (condition-case e (or (ghubp-get-repos-owner-repo (quote ((owner (login . "anquegi")) (name . ".emacs.public.d")))) (and (not magithub--api-available-p) sparse)) (ghub-404 nil))
  eval((condition-case e (or (ghubp-get-repos-owner-repo (quote ((owner (login . "anquegi")) (name . ".emacs.public.d")))) (and (not magithub--api-available-p) sparse)) (ghub-404 nil)))
  magithub-cache(:repo-demographics (condition-case e (or (ghubp-get-repos-owner-repo (quote ((owner (login . "anquegi")) (name . ".emacs.public.d")))) (and (not magithub--api-available-p) sparse)) (ghub-404 nil)) nil :context nil)
  magithub-source-repo()
  magithub-usable-p()
  magithub-maybe-report-offline-mode()
  funcall(magithub-maybe-report-offline-mode)
  (while (and (setq wrapper (car-safe (prog1 magit-insert-headers-hook (setq magit-insert-headers-hook (cdr magit-insert-headers-hook))))) (= (point) (point-min))) (funcall wrapper))
  (let ((magit-insert-section-hook (cons (quote magit-insert-remaining-headers) (if (listp magit-insert-section-hook) magit-insert-section-hook (list magit-insert-section-hook)))) (magit-insert-headers-hook hooks) wrapper) (while (and (setq wrapper (car-safe (prog1 magit-insert-headers-hook (setq magit-insert-headers-hook (cdr magit-insert-headers-hook))))) (= (point) (point-min))) (funcall wrapper)))
  magit-insert-headers((magithub-maybe-report-offline-mode magit-insert-error-header magit-insert-diff-filter-header magit-insert-head-branch-header magit-insert-upstream-branch-header magit-insert-push-branch-header magit-insert-tags-header magithub-maybe-insert-ci-status-header))
  (if (magit-rev-verify "HEAD") (magit-insert-headers magit-status-headers-hook) (insert "In the beginning there was darkness\n\n"))
  magit-insert-status-headers()
  run-hooks(magit-status-sections-hook)
  (if it (progn (message "`%s' contains entries that are no longer valid.\n%s\nUsing standard value instead.  Please re-configure hook variable." hook (mapconcat (function (lambda (sym) (format "  `%s'" sym))) it "\n")) (sit-for 5) (defvar magit--hook-standard-value nil) (let ((magit--hook-standard-value (eval (car (get hook ...))))) (run-hooks (quote magit---hook-standard-value)))) (run-hooks hook))
  (let ((it (-remove (function functionp) (symbol-value hook)))) (if it (progn (message "`%s' contains entries that are no longer valid.\n%s\nUsing standard value instead.  Please re-configure hook variable." hook (mapconcat (function (lambda (sym) (format "  `%s'" sym))) it "\n")) (sit-for 5) (defvar magit--hook-standard-value nil) (let ((magit--hook-standard-value (eval (car ...)))) (run-hooks (quote magit---hook-standard-value)))) (run-hooks hook)))
  magit-run-section-hook(magit-status-sections-hook)
  (catch (quote cancel-section) (magit-run-section-hook (quote magit-status-sections-hook)) (run-hooks (quote magit-insert-section-hook)) (magit-insert-child-count section113) (set-marker-insertion-type (progn nil (or (progn nil (and (vectorp section113) (>= (length section113) 14) (memq (aref section113 0) cl-struct-magit-section-tags) t)) (signal (quote wrong-type-argument) (list (quote magit-section) section113))) (aref section113 3)) t) (let* ((end (progn nil (or (progn nil (and ... ... ... t)) (signal (quote wrong-type-argument) (list ... section113))) (let* ((v section113)) (aset v 5 (point-marker))))) (map (intern (format "magit-%s-section-map" (progn nil (or ... ...) (aref section113 1))))) (map (and (boundp map) (symbol-value map)))) (save-excursion (goto-char (progn nil (or (progn nil (and ... ... ... t)) (signal (quote wrong-type-argument) (list ... section113))) (aref section113 3))) (while (< (point) end) (let ((next (or ... end))) (if (get-text-property (point) (quote magit-section)) nil (put-text-property (point) next (quote magit-section) section113) (if map (progn ...))) (goto-char next))))) (if (eq section113 magit-root-section) (magit-section-show section113) (progn nil (or (progn nil (and (vectorp (progn nil ... ...)) (>= (length ...) 14) (memq (aref ... 0) cl-struct-magit-section-tags) t)) (signal (quote wrong-type-argument) (list (quote magit-section) (progn nil (or ... ...) (aref section113 12))))) (let* ((v (progn nil (or ... ...) (aref section113 12)))) (aset v 13 (nconc (progn nil (or ... ...) (aref ... 13)) (list section113)))))))
  (let ((magit-insert-section--current section113) (magit-insert-section--parent section113) (magit-insert-section--oldroot (or magit-insert-section--oldroot (if magit-insert-section--parent nil (prog1 magit-root-section (setq magit-root-section section113)))))) (catch (quote cancel-section) (magit-run-section-hook (quote magit-status-sections-hook)) (run-hooks (quote magit-insert-section-hook)) (magit-insert-child-count section113) (set-marker-insertion-type (progn nil (or (progn nil (and (vectorp section113) (>= ... 14) (memq ... cl-struct-magit-section-tags) t)) (signal (quote wrong-type-argument) (list (quote magit-section) section113))) (aref section113 3)) t) (let* ((end (progn nil (or (progn nil ...) (signal ... ...)) (let* (...) (aset v 5 ...)))) (map (intern (format "magit-%s-section-map" (progn nil ... ...)))) (map (and (boundp map) (symbol-value map)))) (save-excursion (goto-char (progn nil (or (progn nil ...) (signal ... ...)) (aref section113 3))) (while (< (point) end) (let ((next ...)) (if (get-text-property ... ...) nil (put-text-property ... next ... section113) (if map ...)) (goto-char next))))) (if (eq section113 magit-root-section) (magit-section-show section113) (progn nil (or (progn nil (and (vectorp ...) (>= ... 14) (memq ... cl-struct-magit-section-tags) t)) (signal (quote wrong-type-argument) (list (quote magit-section) (progn nil ... ...)))) (let* ((v (progn nil ... ...))) (aset v 13 (nconc (progn nil ... ...) (list section113))))))) section113)
  (let* ((section113 (progn "Constructor for objects of type `magit-section'." nil (vector (quote cl-struct-magit-section) (quote status) nil (point-marker) nil nil nil nil nil nil nil nil magit-insert-section--parent nil)))) (progn nil (or (progn nil (and (vectorp section113) (>= (length section113) 14) (memq (aref section113 0) cl-struct-magit-section-tags) t)) (signal (quote wrong-type-argument) (list (quote magit-section) section113))) (let* ((v section113)) (aset v 6 (let ((value (run-hook-with-args-until-success ... section113))) (if value (eq value (quote hide)) (let (...) (if it ... nil))))))) (let ((magit-insert-section--current section113) (magit-insert-section--parent section113) (magit-insert-section--oldroot (or magit-insert-section--oldroot (if magit-insert-section--parent nil (prog1 magit-root-section (setq magit-root-section section113)))))) (catch (quote cancel-section) (magit-run-section-hook (quote magit-status-sections-hook)) (run-hooks (quote magit-insert-section-hook)) (magit-insert-child-count section113) (set-marker-insertion-type (progn nil (or (progn nil (and ... ... ... t)) (signal (quote wrong-type-argument) (list ... section113))) (aref section113 3)) t) (let* ((end (progn nil (or ... ...) (let* ... ...))) (map (intern (format "magit-%s-section-map" ...))) (map (and (boundp map) (symbol-value map)))) (save-excursion (goto-char (progn nil (or ... ...) (aref section113 3))) (while (< (point) end) (let (...) (if ... nil ... ...) (goto-char next))))) (if (eq section113 magit-root-section) (magit-section-show section113) (progn nil (or (progn nil (and ... ... ... t)) (signal (quote wrong-type-argument) (list ... ...))) (let* ((v ...)) (aset v 13 (nconc ... ...)))))) section113))
  magit-status-refresh-buffer()
  apply(magit-status-refresh-buffer nil)
  (save-excursion (apply refresh magit-refresh-args))
  (let ((inhibit-read-only t)) (erase-buffer) (save-excursion (apply refresh magit-refresh-args)))
  (let* ((buffer (current-buffer)) (windows (apply (quote append) (mapcar (function (lambda (it) (let ... ...))) (or (get-buffer-window-list buffer nil t) (list (selected-window))))))) (deactivate-mark) (setq magit-section-highlight-overlays nil) (setq magit-section-highlighted-section nil) (setq magit-section-highlighted-sections nil) (setq magit-section-unhighlight-sections nil) (let ((inhibit-read-only t)) (erase-buffer) (save-excursion (apply refresh magit-refresh-args))) (let ((--dolist-tail-- windows)) (while --dolist-tail-- (let ((window (car --dolist-tail--))) (let ((save-selected-window--state (internal--before-with-selected-window ...))) (save-current-buffer (unwind-protect (progn ... ...) (internal--after-with-selected-window save-selected-window--state)))) (setq --dolist-tail-- (cdr --dolist-tail--))))) (run-hooks (quote magit-refresh-buffer-hook)) (magit-section-update-highlight) (set-buffer-modified-p nil))
  (progn (if magit-refresh-verbose (progn (message "Refreshing buffer `%s'..." (buffer-name)))) (let* ((buffer (current-buffer)) (windows (apply (quote append) (mapcar (function (lambda ... ...)) (or (get-buffer-window-list buffer nil t) (list ...)))))) (deactivate-mark) (setq magit-section-highlight-overlays nil) (setq magit-section-highlighted-section nil) (setq magit-section-highlighted-sections nil) (setq magit-section-unhighlight-sections nil) (let ((inhibit-read-only t)) (erase-buffer) (save-excursion (apply refresh magit-refresh-args))) (let ((--dolist-tail-- windows)) (while --dolist-tail-- (let ((window (car --dolist-tail--))) (let ((save-selected-window--state ...)) (save-current-buffer (unwind-protect ... ...))) (setq --dolist-tail-- (cdr --dolist-tail--))))) (run-hooks (quote magit-refresh-buffer-hook)) (magit-section-update-highlight) (set-buffer-modified-p nil)) (if magit-refresh-verbose (progn (message "Refreshing buffer `%s'...done (%.3fs)" (buffer-name) (float-time (time-subtract (current-time) magit-refresh-start-time))))))
  (if (functionp refresh) (progn (if magit-refresh-verbose (progn (message "Refreshing buffer `%s'..." (buffer-name)))) (let* ((buffer (current-buffer)) (windows (apply (quote append) (mapcar (function ...) (or ... ...))))) (deactivate-mark) (setq magit-section-highlight-overlays nil) (setq magit-section-highlighted-section nil) (setq magit-section-highlighted-sections nil) (setq magit-section-unhighlight-sections nil) (let ((inhibit-read-only t)) (erase-buffer) (save-excursion (apply refresh magit-refresh-args))) (let ((--dolist-tail-- windows)) (while --dolist-tail-- (let ((window ...)) (let (...) (save-current-buffer ...)) (setq --dolist-tail-- (cdr --dolist-tail--))))) (run-hooks (quote magit-refresh-buffer-hook)) (magit-section-update-highlight) (set-buffer-modified-p nil)) (if magit-refresh-verbose (progn (message "Refreshing buffer `%s'...done (%.3fs)" (buffer-name) (float-time (time-subtract (current-time) magit-refresh-start-time)))))))
  (let ((refresh (intern (format "%s-refresh-buffer" (substring (symbol-name major-mode) 0 -5)))) (magit--refresh-cache (or magit--refresh-cache (list (cons 0 0))))) (if (functionp refresh) (progn (if magit-refresh-verbose (progn (message "Refreshing buffer `%s'..." (buffer-name)))) (let* ((buffer (current-buffer)) (windows (apply (quote append) (mapcar ... ...)))) (deactivate-mark) (setq magit-section-highlight-overlays nil) (setq magit-section-highlighted-section nil) (setq magit-section-highlighted-sections nil) (setq magit-section-unhighlight-sections nil) (let ((inhibit-read-only t)) (erase-buffer) (save-excursion (apply refresh magit-refresh-args))) (let ((--dolist-tail-- windows)) (while --dolist-tail-- (let (...) (let ... ...) (setq --dolist-tail-- ...)))) (run-hooks (quote magit-refresh-buffer-hook)) (magit-section-update-highlight) (set-buffer-modified-p nil)) (if magit-refresh-verbose (progn (message "Refreshing buffer `%s'...done (%.3fs)" (buffer-name) (float-time (time-subtract ... magit-refresh-start-time))))))))
  magit-refresh-buffer()
  (save-current-buffer (set-buffer buffer) (run-hooks (quote magit-mode-setup-hook)) (magit-refresh-buffer))
  (let ((buffer (magit-mode-get-buffer mode t nil (and locked (magit-buffer-lock-value mode args)))) (section (magit-current-section))) (save-current-buffer (set-buffer buffer) (setq magit-previous-section section) (setq magit-refresh-args args) (funcall mode)) (magit-display-buffer buffer) (save-current-buffer (set-buffer buffer) (run-hooks (quote magit-mode-setup-hook)) (magit-refresh-buffer)))
  magit-mode-setup-internal(magit-status-mode nil)
  magit-mode-setup(magit-status-mode)
  (let ((default-directory directory)) (magit-mode-setup (function magit-status-mode)))
  magit-status-internal("/Users/toni/.emacs.d/")
  (if (and toplevel (file-equal-p directory toplevel)) (magit-status-internal directory) (if (y-or-n-p (if toplevel (format "%s is a repository.  Create another in %s? " toplevel directory) (format "Create repository in %s? " directory))) (progn (setq magit--refresh-cache nil) (magit-init directory))))
  (let ((toplevel (magit-toplevel directory))) (setq directory (file-name-as-directory (expand-file-name directory))) (if (and toplevel (file-equal-p directory toplevel)) (magit-status-internal directory) (if (y-or-n-p (if toplevel (format "%s is a repository.  Create another in %s? " toplevel directory) (format "Create repository in %s? " directory))) (progn (setq magit--refresh-cache nil) (magit-init directory)))))
  (if directory (let ((toplevel (magit-toplevel directory))) (setq directory (file-name-as-directory (expand-file-name directory))) (if (and toplevel (file-equal-p directory toplevel)) (magit-status-internal directory) (if (y-or-n-p (if toplevel (format "%s is a repository.  Create another in %s? " toplevel directory) (format "Create repository in %s? " directory))) (progn (setq magit--refresh-cache nil) (magit-init directory))))) (magit-status-internal default-directory))
  (let ((magit--refresh-cache (or cache (list (cons 0 0))))) (if directory (let ((toplevel (magit-toplevel directory))) (setq directory (file-name-as-directory (expand-file-name directory))) (if (and toplevel (file-equal-p directory toplevel)) (magit-status-internal directory) (if (y-or-n-p (if toplevel (format "%s is a repository.  Create another in %s? " toplevel directory) (format "Create repository in %s? " directory))) (progn (setq magit--refresh-cache nil) (magit-init directory))))) (magit-status-internal default-directory)))
  (closure (bookmark-make-record-function t) (&optional directory cache) "Show the status of the current Git repository in a buffer.\nWith a prefix argument prompt for a repository to be shown.\nWith two prefix arguments prompt for an arbitrary directory.\nIf that directory isn't the root of an existing repository,\nthen offer to initialize it as a new repository." (interactive (let ((magit--refresh-cache (list (cons 0 0)))) (list (and (or current-prefix-arg (not (magit-toplevel))) (magit-read-repository (>= (prefix-numeric-value current-prefix-arg) 16))) magit--refresh-cache))) (let ((magit--refresh-cache (or cache (list (cons 0 0))))) (if directory (let ((toplevel (magit-toplevel directory))) (setq directory (file-name-as-directory (expand-file-name directory))) (if (and toplevel (file-equal-p directory toplevel)) (magit-status-internal directory) (if (y-or-n-p (if toplevel ... ...)) (progn (setq magit--refresh-cache nil) (magit-init directory))))) (magit-status-internal default-directory))))("~/.emacs.d/" ((21 . 11) (("/Users/toni/.emacs.d/" "rev-parse" "--verify" "HEAD") . "1b2e82c62a4a2f2262c39c205c9493084eed4dde") (("/Users/toni/.emacs.d/" "ls-remote" "--get-url" "origin") . "git@github.com:anquegi/.emacs.public.d.git") ((config "/Users/toni/.emacs.d/") . #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ("credential.helper" ("osxkeychain") "user.email" ("antonio.querol@cuaqea.com") "user.name" ("Toni") "github.user" ("anquegi@gmail.com") "core.repositoryformatversion" ("0") "core.filemode" ("true") "core.bare" ("false") "core.logallrefupdates" ("true") "core.ignorecase" ("true") "core.precomposeunicode" ("true") "remote.origin.url" ("git@github.com:anquegi/.emacs.public.d.git") "remote.origin.fetch" ("+refs/heads/*:refs/remotes/origin/*") "branch.master.remote" ("origin") "branch.master.merge" ("refs/heads/master") "core.preloadindex" ("true") "log.showsignature" ("false") ...))) (("/Users/toni/.emacs.d/" "rev-parse" "--is-bare-repository") . "false") (("/Users/toni/.emacs.d/" . magit-toplevel) . "/Users/toni/.emacs.d/") (("~/.emacs.d/" . magit-toplevel) . "/Users/toni/.emacs.d/") (("/Users/toni/.emacs.d/" "rev-parse" "--show-cdup") . "") (("/Users/toni/.emacs.d/" "rev-parse" "--show-toplevel") . "/Users/toni/.emacs.d") (("~/" . magit-toplevel)) (("/Users/toni/" "rev-parse" "--git-dir")) (("/Users/toni/" "rev-parse" "--show-toplevel"))))
  apply((closure (bookmark-make-record-function t) (&optional directory cache) "Show the status of the current Git repository in a buffer.\nWith a prefix argument prompt for a repository to be shown.\nWith two prefix arguments prompt for an arbitrary directory.\nIf that directory isn't the root of an existing repository,\nthen offer to initialize it as a new repository." (interactive (let ((magit--refresh-cache (list (cons 0 0)))) (list (and (or current-prefix-arg (not (magit-toplevel))) (magit-read-repository (>= (prefix-numeric-value current-prefix-arg) 16))) magit--refresh-cache))) (let ((magit--refresh-cache (or cache (list (cons 0 0))))) (if directory (let ((toplevel (magit-toplevel directory))) (setq directory (file-name-as-directory (expand-file-name directory))) (if (and toplevel (file-equal-p directory toplevel)) (magit-status-internal directory) (if (y-or-n-p (if toplevel ... ...)) (progn (setq magit--refresh-cache nil) (magit-init directory))))) (magit-status-internal default-directory)))) ("~/.emacs.d/" ((21 . 11) (("/Users/toni/.emacs.d/" "rev-parse" "--verify" "HEAD") . "1b2e82c62a4a2f2262c39c205c9493084eed4dde") (("/Users/toni/.emacs.d/" "ls-remote" "--get-url" "origin") . "git@github.com:anquegi/.emacs.public.d.git") ((config "/Users/toni/.emacs.d/") . #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ("credential.helper" ("osxkeychain") "user.email" ("antonio.querol@cuaqea.com") "user.name" ("Toni") "github.user" ("anquegi@gmail.com") "core.repositoryformatversion" ("0") "core.filemode" ("true") "core.bare" ("false") "core.logallrefupdates" ("true") "core.ignorecase" ("true") "core.precomposeunicode" ("true") "remote.origin.url" ("git@github.com:anquegi/.emacs.public.d.git") "remote.origin.fetch" ("+refs/heads/*:refs/remotes/origin/*") "branch.master.remote" ("origin") "branch.master.merge" ("refs/heads/master") "core.preloadindex" ("true") "log.showsignature" ("false") ...))) (("/Users/toni/.emacs.d/" "rev-parse" "--is-bare-repository") . "false") (("/Users/toni/.emacs.d/" . magit-toplevel) . "/Users/toni/.emacs.d/") (("~/.emacs.d/" . magit-toplevel) . "/Users/toni/.emacs.d/") (("/Users/toni/.emacs.d/" "rev-parse" "--show-cdup") . "") (("/Users/toni/.emacs.d/" "rev-parse" "--show-toplevel") . "/Users/toni/.emacs.d") (("~/" . magit-toplevel)) (("/Users/toni/" "rev-parse" "--git-dir")) (("/Users/toni/" "rev-parse" "--show-toplevel")))))
  (let ((fullframe/--window-config170 (current-window-configuration))) (apply orig-fun args) (let ((fullframe/--window-config-post171 (current-window-configuration))) (delete-other-windows) (if (equal fullframe/--window-config-post171 (current-window-configuration)) nil (setq fullframe/previous-window-configuration fullframe/--window-config170))))
  (closure (t) (orig-fun &rest args) (let ((fullframe/--window-config170 (current-window-configuration))) (apply orig-fun args) (let ((fullframe/--window-config-post171 (current-window-configuration))) (delete-other-windows) (if (equal fullframe/--window-config-post171 (current-window-configuration)) nil (setq fullframe/previous-window-configuration fullframe/--window-config170)))))((closure (bookmark-make-record-function t) (&optional directory cache) "Show the status of the current Git repository in a buffer.\nWith a prefix argument prompt for a repository to be shown.\nWith two prefix arguments prompt for an arbitrary directory.\nIf that directory isn't the root of an existing repository,\nthen offer to initialize it as a new repository." (interactive (let ((magit--refresh-cache (list (cons 0 0)))) (list (and (or current-prefix-arg (not (magit-toplevel))) (magit-read-repository (>= (prefix-numeric-value current-prefix-arg) 16))) magit--refresh-cache))) (let ((magit--refresh-cache (or cache (list (cons 0 0))))) (if directory (let ((toplevel (magit-toplevel directory))) (setq directory (file-name-as-directory (expand-file-name directory))) (if (and toplevel (file-equal-p directory toplevel)) (magit-status-internal directory) (if (y-or-n-p (if toplevel ... ...)) (progn (setq magit--refresh-cache nil) (magit-init directory))))) (magit-status-internal default-directory)))) "~/.emacs.d/" ((21 . 11) (("/Users/toni/.emacs.d/" "rev-parse" "--verify" "HEAD") . "1b2e82c62a4a2f2262c39c205c9493084eed4dde") (("/Users/toni/.emacs.d/" "ls-remote" "--get-url" "origin") . "git@github.com:anquegi/.emacs.public.d.git") ((config "/Users/toni/.emacs.d/") . #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ("credential.helper" ("osxkeychain") "user.email" ("antonio.querol@cuaqea.com") "user.name" ("Toni") "github.user" ("anquegi@gmail.com") "core.repositoryformatversion" ("0") "core.filemode" ("true") "core.bare" ("false") "core.logallrefupdates" ("true") "core.ignorecase" ("true") "core.precomposeunicode" ("true") "remote.origin.url" ("git@github.com:anquegi/.emacs.public.d.git") "remote.origin.fetch" ("+refs/heads/*:refs/remotes/origin/*") "branch.master.remote" ("origin") "branch.master.merge" ("refs/heads/master") "core.preloadindex" ("true") "log.showsignature" ("false") ...))) (("/Users/toni/.emacs.d/" "rev-parse" "--is-bare-repository") . "false") (("/Users/toni/.emacs.d/" . magit-toplevel) . "/Users/toni/.emacs.d/") (("~/.emacs.d/" . magit-toplevel) . "/Users/toni/.emacs.d/") (("/Users/toni/.emacs.d/" "rev-parse" "--show-cdup") . "") (("/Users/toni/.emacs.d/" "rev-parse" "--show-toplevel") . "/Users/toni/.emacs.d") (("~/" . magit-toplevel)) (("/Users/toni/" "rev-parse" "--git-dir")) (("/Users/toni/" "rev-parse" "--show-toplevel"))))
  apply((closure (t) (orig-fun &rest args) (let ((fullframe/--window-config170 (current-window-configuration))) (apply orig-fun args) (let ((fullframe/--window-config-post171 (current-window-configuration))) (delete-other-windows) (if (equal fullframe/--window-config-post171 (current-window-configuration)) nil (setq fullframe/previous-window-configuration fullframe/--window-config170))))) (closure (bookmark-make-record-function t) (&optional directory cache) "Show the status of the current Git repository in a buffer.\nWith a prefix argument prompt for a repository to be shown.\nWith two prefix arguments prompt for an arbitrary directory.\nIf that directory isn't the root of an existing repository,\nthen offer to initialize it as a new repository." (interactive (let ((magit--refresh-cache (list (cons 0 0)))) (list (and (or current-prefix-arg (not (magit-toplevel))) (magit-read-repository (>= (prefix-numeric-value current-prefix-arg) 16))) magit--refresh-cache))) (let ((magit--refresh-cache (or cache (list (cons 0 0))))) (if directory (let ((toplevel (magit-toplevel directory))) (setq directory (file-name-as-directory (expand-file-name directory))) (if (and toplevel (file-equal-p directory toplevel)) (magit-status-internal directory) (if (y-or-n-p (if toplevel ... ...)) (progn (setq magit--refresh-cache nil) (magit-init directory))))) (magit-status-internal default-directory)))) ("~/.emacs.d/" ((21 . 11) (("/Users/toni/.emacs.d/" "rev-parse" "--verify" "HEAD") . "1b2e82c62a4a2f2262c39c205c9493084eed4dde") (("/Users/toni/.emacs.d/" "ls-remote" "--get-url" "origin") . "git@github.com:anquegi/.emacs.public.d.git") ((config "/Users/toni/.emacs.d/") . #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ("credential.helper" ("osxkeychain") "user.email" ("antonio.querol@cuaqea.com") "user.name" ("Toni") "github.user" ("anquegi@gmail.com") "core.repositoryformatversion" ("0") "core.filemode" ("true") "core.bare" ("false") "core.logallrefupdates" ("true") "core.ignorecase" ("true") "core.precomposeunicode" ("true") "remote.origin.url" ("git@github.com:anquegi/.emacs.public.d.git") "remote.origin.fetch" ("+refs/heads/*:refs/remotes/origin/*") "branch.master.remote" ("origin") "branch.master.merge" ("refs/heads/master") "core.preloadindex" ("true") "log.showsignature" ("false") ...))) (("/Users/toni/.emacs.d/" "rev-parse" "--is-bare-repository") . "false") (("/Users/toni/.emacs.d/" . magit-toplevel) . "/Users/toni/.emacs.d/") (("~/.emacs.d/" . magit-toplevel) . "/Users/toni/.emacs.d/") (("/Users/toni/.emacs.d/" "rev-parse" "--show-cdup") . "") (("/Users/toni/.emacs.d/" "rev-parse" "--show-toplevel") . "/Users/toni/.emacs.d") (("~/" . magit-toplevel)) (("/Users/toni/" "rev-parse" "--git-dir")) (("/Users/toni/" "rev-parse" "--show-toplevel")))))
  magit-status("~/.emacs.d/" ((21 . 11) (("/Users/toni/.emacs.d/" "rev-parse" "--verify" "HEAD") . "1b2e82c62a4a2f2262c39c205c9493084eed4dde") (("/Users/toni/.emacs.d/" "ls-remote" "--get-url" "origin") . "git@github.com:anquegi/.emacs.public.d.git") ((config "/Users/toni/.emacs.d/") . #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ("credential.helper" ("osxkeychain") "user.email" ("antonio.querol@cuaqea.com") "user.name" ("Toni") "github.user" ("anquegi@gmail.com") "core.repositoryformatversion" ("0") "core.filemode" ("true") "core.bare" ("false") "core.logallrefupdates" ("true") "core.ignorecase" ("true") "core.precomposeunicode" ("true") "remote.origin.url" ("git@github.com:anquegi/.emacs.public.d.git") "remote.origin.fetch" ("+refs/heads/*:refs/remotes/origin/*") "branch.master.remote" ("origin") "branch.master.merge" ("refs/heads/master") "core.preloadindex" ("true") "log.showsignature" ("false") ...))) (("/Users/toni/.emacs.d/" "rev-parse" "--is-bare-repository") . "false") (("/Users/toni/.emacs.d/" . magit-toplevel) . "/Users/toni/.emacs.d/") (("~/.emacs.d/" . magit-toplevel) . "/Users/toni/.emacs.d/") (("/Users/toni/.emacs.d/" "rev-parse" "--show-cdup") . "") (("/Users/toni/.emacs.d/" "rev-parse" "--show-toplevel") . "/Users/toni/.emacs.d") (("~/" . magit-toplevel)) (("/Users/toni/" "rev-parse" "--git-dir")) (("/Users/toni/" "rev-parse" "--show-toplevel"))))
  funcall-interactively(magit-status "~/.emacs.d/" ((21 . 11) (("/Users/toni/.emacs.d/" "rev-parse" "--verify" "HEAD") . "1b2e82c62a4a2f2262c39c205c9493084eed4dde") (("/Users/toni/.emacs.d/" "ls-remote" "--get-url" "origin") . "git@github.com:anquegi/.emacs.public.d.git") ((config "/Users/toni/.emacs.d/") . #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ("credential.helper" ("osxkeychain") "user.email" ("antonio.querol@cuaqea.com") "user.name" ("Toni") "github.user" ("anquegi@gmail.com") "core.repositoryformatversion" ("0") "core.filemode" ("true") "core.bare" ("false") "core.logallrefupdates" ("true") "core.ignorecase" ("true") "core.precomposeunicode" ("true") "remote.origin.url" ("git@github.com:anquegi/.emacs.public.d.git") "remote.origin.fetch" ("+refs/heads/*:refs/remotes/origin/*") "branch.master.remote" ("origin") "branch.master.merge" ("refs/heads/master") "core.preloadindex" ("true") "log.showsignature" ("false") ...))) (("/Users/toni/.emacs.d/" "rev-parse" "--is-bare-repository") . "false") (("/Users/toni/.emacs.d/" . magit-toplevel) . "/Users/toni/.emacs.d/") (("~/.emacs.d/" . magit-toplevel) . "/Users/toni/.emacs.d/") (("/Users/toni/.emacs.d/" "rev-parse" "--show-cdup") . "") (("/Users/toni/.emacs.d/" "rev-parse" "--show-toplevel") . "/Users/toni/.emacs.d") (("~/" . magit-toplevel)) (("/Users/toni/" "rev-parse" "--git-dir")) (("/Users/toni/" "rev-parse" "--show-toplevel"))))
  call-interactively(magit-status nil nil)
  command-execute(magit-status)
```

Thanks for your help

**Comment by vermiculus** [comment] 2017-08-17 15:22
Duplicate of #127.

There are instructions there 👍

**Closed by vermiculus** 2017-08-17 15:22 UTC
