### ISSUE TITLE
Can magithub support GitHub notifications?

### ISSUE THREAD

**Issue by stardiviner** [vermiculus/magithub#140] opened 2017-09-12 11:35 UTC
Is it possible to let magithub support https://github.com/notifications/participating ?

**Comment by vermiculus** [comment] 2017-09-12 15:04
It's in the plan 😄

**Comment by vermiculus** [comment] 2017-10-08 18:50
Closing as a duplicate of #96.

**Closed by vermiculus** 2017-10-08 18:50 UTC
Labels: enhancement

**Comment by vermiculus** [comment] 2017-10-21 04:08
Just a ping -- this is a thing now 😄 check out `M-x magithub-dashboard`.
