### ISSUE TITLE
`magithub-source-repo` call fails because of undefined function

### ISSUE THREAD

**Issue by rjprins** [vermiculus/magithub#127] opened 2017-08-17 08:48 UTC
It seems magithub expects a ghub+ function to exist, but it doesn't.

`apply: Symbol’s function definition is void: nil`

I think this is because `magithub-source-repo` calls `magithub-cache` with a `ghubp-get-repos-owner-repo` function in it's arguments, but `ghubp-get-repos-owner-repo` is not defined.

Versions:
```
  ghub               20170803.601
  ghub+              20170815.2027
  magithub           20170810.1947
  magit              20170808.1712
```

```
Debugger entered--Lisp error: (void-function nil)
  nil("/repos/myself/my-repo" nil nil)
  apply(nil "/repos/myself/my-repo" (nil nil))
  ghubp-get-repos-owner-repo(((owner (login . "myself")) (name . "my-repo")))
  (or (ghubp-get-repos-owner-repo (quote ((owner (login . "myself")) (name . "my-repo")))) (and (not magithub--api-available-p) sparse))
  (condition-case e (or (ghubp-get-repos-owner-repo (quote ((owner (login . "myself")) (name . "my-repo")))) (and (not magithub--api-available-p) sparse)) (ghub-404 nil))
  eval((condition-case e (or (ghubp-get-repos-owner-repo (quote ((owner (login . "myself")) (name . "my-repo")))) (and (not magithub--api-available-p) sparse)) (ghub-404 nil)))
  magithub-cache(:repo-demographics (condition-case e (or (ghubp-get-repos-owner-repo (quote ((owner (login . "myself")) (name . "my-repo")))) (and (not magithub--api-available-p) sparse)) (ghub-404 nil)) nil :context nil)
  magithub-source-repo()
  magithub-usable-p()
  magithub-maybe-report-offline-mode()
  magit-insert-headers((magithub-maybe-report-offline-mode magit-insert-error-header magit-insert-diff-filter-header magit-insert-head-branch-header magit-insert-upstream-branch-header magit-insert-push-branch-header magit-insert-tags-header magithub-maybe-insert-ci-status-header))
  magit-insert-status-headers()
  run-hooks(magit-status-sections-hook)
  magit-run-section-hook(magit-status-sections-hook)
  magit-status-refresh-buffer()
  apply(magit-status-refresh-buffer nil)
  magit-refresh-buffer()
  magit-mode-setup-internal(magit-status-mode nil)
  magit-mode-setup(magit-status-mode)
  magit-status-internal("/home/myself/my-repo/")
```

**Comment by vermiculus** [comment] 2017-08-17 12:31
Are you sure this isn't vermiculus/ghub-plus#3? That was solved just by re-updating. (There were apparently some timing issues with the MELPA push.)

**Comment by vermiculus** [comment] 2017-08-17 12:36
The issue is not that `ghubp-get-repos-owner-repo` is not defined (if you look at your backtrace, it's there), the issue is that ghub+ was updated before apiwrap.el was. The previous version of apiwrap.el looked for `:get`, `:put`, … keywords in the `apiwrap-new-backend` function, but the updated version just uses a single `:request` keyword for the generic request function (i.e., `ghub-request`). When apiwrap.el built out the ghub+ functions, it wasn't able to retrieve the `:get` function, so `(alist-get 'get functions)` returned nil, so we tried to call a nil function.

**Comment by anquegi** [comment] 2017-08-17 15:37
Thanks for your quickreply I tried to update with:
```

cask --verbose update                                                                                                                                                                                    
Importing package-keyring.gpg...
Importing package-keyring.gpg...done
```


and nothing happens

my repos on Cask file are:
```

(source "gnu" "http://elpa.gnu.org/packages/")
(source "melpa" "http://melpa.milkbox.net/packages/")
(source "marmalade" "https://marmalade-repo.org/packages/")
(source "org" "http://orgmode.org/elpa/")
```

should I change the order

**Comment by vermiculus** [comment] 2017-08-17 18:10
You might just try deleting the packages from `M-x list-packages` and re-installing. It probably doesn't think re-compiling is necessary.

**Comment by anquegi** [comment] 2017-08-18 06:02
@vermiculus, you were right I delete the .cask directory and reinstall all packages, now it works, thanks

**Comment by rjprins** [comment] 2017-08-18 07:55
@vermiculus Thanks for the help! Reinstalling also solved the issue for me.

**Comment by vermiculus** [comment] 2017-08-18 12:02
Closing as a duplicate of vermiculus/ghub-plus#3.

**Closed by vermiculus** 2017-08-18 12:02 UTC
